### ISSUE TITLE
can work ?

### ISSUE THREAD

**Issue by ghost** [matt-dechicio/ethos-rig-watchdog#1]
Will your article here is working on the 1.2.9 version of the above?
Looking forward to your reply !

**Comment by matt-dechicio** [comment]
Yes. I use it for my own rig and it's running at version 1.2.9

**Comment by ghost** [comment]
iam try read your setup 
i input the command 「sudo apt-get install docker」
i get a error 「WARNING: Upgrading, updating, and/or installing packages with apt-get is unsupported and will likely break ethOS. If you still want to apt-get, use apt-get-ubuntu. install docker」
No problem?

**Comment by matt-dechicio** [comment]
The watchdog needs to be installed on a machine outside of your ethos rigs. Unfortunately my time is limited and I won't be able to make a tutorial.
